sample_sheet_path: "/n/groups/kwon/mzhu/pipelines/my_rnaseq_run/rnaseq_gene_expression-main/input/sample_sheet.csv"
sample_sheet_batch_size: 1000
kraken_db_path: "/n/scratch/users/j/je112/kraken_db"
skip_kraken: "true"
min_target_reads: 100000
target_species: "Homo sapiens"
ensembl_version: 115

